version: "3.5"

services:
  geppetto:
    build: .
    container_name: geppetto
    volumes:
      - "./config:/app/config" #To customize with your own config folder.

# Remove the following lines if you don't want to use Ollama environment
#     environment:
#       - OLLAMA_BASE_URL=http://ollama:11434
#     depends_on:
#       - ollama

#   ollama:
#     image: ollama/ollama:latest
#     container_name: ollama
#     volumes:
#       - ollama:/root/.ollama
#     ports:
#       - "11434:11434"
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]

# volumes:
#   ollama:
